# Generated by Django 4.0.6 on 2022-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1975-12-12'),
            preserve_default=False,
        ),
    ]
